services:
  namenode:
    image: apache/hadoop:3.5.0
    container_name: namenode
    hostname: namenode
    user: root
    env_file:
      - ./.env
    volumes:
      - ./config/hadoop:/opt/hadoop/etc/hadoop
      - ./scripts:/scripts
    ports:
      - "9870:9870"
      - "8020:8020"
    restart: unless-stopped
    networks:
      - dev
    command: ["/bin/bash", "/scripts/start-hdfs.sh"]
  datanode1:
    image: apache/hadoop:3.5.0
    container_name: datanode1
    hostname: datanode1
    user: root
    env_file:
      - ./.env
    volumes:
      - ./config/hadoop:/opt/hadoop/etc/hadoop
      - ./scripts:/scripts
    depends_on:
      - namenode
    restart: unless-stopped
    networks:
      - dev
    command: ["/bin/bash", "/scripts/init-datanode.sh"]
  datanode2:
    image: apache/hadoop:3.5.0
    container_name: datanode2
    hostname: datanode2
    user: root
    env_file:
      - ./.env
    volumes:
      - ./config/hadoop:/opt/hadoop/etc/hadoop
      - ./scripts:/scripts
    depends_on:
      - namenode
    restart: unless-stopped
    networks:
      - dev
    command: ["/bin/bash", "/scripts/init-datanode.sh"]
  datanode3:
    image: apache/hadoop:3.5.0
    container_name: datanode3
    hostname: datanode3
    user: root
    env_file:
      - ./.env
    volumes:
      - ./config/hadoop:/opt/hadoop/etc/hadoop
      - ./scripts:/scripts
    depends_on:
      - namenode
    restart: unless-stopped
    networks:
      - dev
    command: ["/bin/bash", "/scripts/init-datanode.sh"]
  resourcemanager:
    image: apache/hadoop:3.5.0
    hostname: resourcemanager
    container_name: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./.env
    networks:
      - dev
  nodemanager:
    image: apache/hadoop:3.5.0
    container_name: nodemanager
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - dev
  proxy:
    image: apache/hadoop:3.5.0
    container_name: proxy
    hostname: proxy
    user: root
    env_file:
      - ./.env
    volumes:
      - ./config/hadoop:/opt/hadoop/etc/hadoop
    depends_on:
      - namenode
    ports:
      - "14000:14000"
    restart: unless-stopped
    networks:
      - dev
    command: ["hdfs", "httpfs"]

networks:
  dev:
    driver: bridge
